using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Mirror;

public class SmallCity : MonoBehaviour
{
	public bool isSelected = false;
	public bool InvOpen = false;
	public bool MobilizationInProgress = false;
	public bool ResearchPanelIsActive = false;
	public string cityName;
	public int cityID;
	public int turnToResearch;
    public int ownerPlayerID;
	public int Population;
	public int PopulationWorkable;
	public int PopulationAP;
	public int PopulationMaxAP;
    public CityInventory cityInventory;
	public CellData currentCell;
	public Node currentNode;
	public PlayerScript playerScript;
	public GameObject ThisCity;
	public int GlobalID;
	public string spritePath;
	public int aIDefendDrone1;
	public int aIDefendDrone2;
	public int aIAttackDrone1;
	public int aIAttackDrone2;
	public int aIAttackDrone3;
	
	public int PopulationAge0M;
	public int PopulationAge0W;
	public int PopulationAge1M;
	public int PopulationAge1W;
	public int PopulationAge2M;
	public int PopulationAge2W;
	public int PopulationAge3M;
	public int PopulationAge3W;
	public int PopulationAge4M;
	public int PopulationAge4W;
	public int PopulationAge5M;
	public int PopulationAge5W;
	public int PopulationAge6M;
	public int PopulationAge6W;
	public int PopulationAge7M;
	public int PopulationAge7W;
	public int PopulationAge8M;
	public int PopulationAge8W;
	public int PopulationAge9M;
	public int PopulationAge9W;
	public int PopulationAge10M;
	public int PopulationAge10W;
	public int PopulationAge11M;
	public int PopulationAge11W;
	public int PopulationAge12M;
	public int PopulationAge12W;
	public int PopulationAge13M;
	public int PopulationAge13W;
	public int PopulationAge14M;
	public int PopulationAge14W;
	public int PopulationAge15M;
	public int PopulationAge15W;
	public int PopulationAge16M;
	public int PopulationAge16W;
	public int PopulationAge17M;
	public int PopulationAge17W;
	public int PopulationAge18M;
	public int PopulationAge18W;
	public int PopulationAge19M;
	public int PopulationAge19W;
	public int PopulationAge20M;
	public int PopulationAge20W;
	public int PopulationAge21M;
	public int PopulationAge21W;
	public int PopulationAge22M;
	public int PopulationAge22W;
	public int PopulationAge23M;
	public int PopulationAge23W;
	public int PopulationAge24M;
	public int PopulationAge24W;
	public int PopulationAge25M;
	public int PopulationAge25W;
	public int PopulationAge26M;
	public int PopulationAge26W;
	public int PopulationAge27M;
	public int PopulationAge27W;
	public int PopulationAge28M;
	public int PopulationAge28W;
	public int PopulationAge29M;
	public int PopulationAge29W;
	public int PopulationAge30M;
	public int PopulationAge30W;
	public int PopulationAge31M;
	public int PopulationAge31W;
	public int PopulationAge32M;
	public int PopulationAge32W;
	public int PopulationAge33M;
	public int PopulationAge33W;
	public int PopulationAge34M;
	public int PopulationAge34W;
	public int PopulationAge35M;
	public int PopulationAge35W;
	public int PopulationAge36M;
	public int PopulationAge36W;
	public int PopulationAge37M;
	public int PopulationAge37W;
	public int PopulationAge38M;
	public int PopulationAge38W;
	public int PopulationAge39M;
	public int PopulationAge39W;
	public int PopulationAge40M;
	public int PopulationAge40W;
	public int PopulationAge41M;
	public int PopulationAge41W;
	public int PopulationAge42M;
	public int PopulationAge42W;
	public int PopulationAge43M;
	public int PopulationAge43W;
	public int PopulationAge44M;
	public int PopulationAge44W;
	public int PopulationAge45M;
	public int PopulationAge45W;
	public int PopulationAge46M;
	public int PopulationAge46W;
	public int PopulationAge47M;
	public int PopulationAge47W;
	public int PopulationAge48M;
	public int PopulationAge48W;
	public int PopulationAge49M;
	public int PopulationAge49W;
	public int PopulationAge50M;
	public int PopulationAge50W;
	public int PopulationAge51M;
	public int PopulationAge51W;
	public int PopulationAge52M;
	public int PopulationAge52W;
	public int PopulationAge53M;
	public int PopulationAge53W;
	public int PopulationAge54M;
	public int PopulationAge54W;
	public int PopulationAge55M;
	public int PopulationAge55W;
	public int PopulationAge56M;
	public int PopulationAge56W;
	public int PopulationAge57M;
	public int PopulationAge57W;
	public int PopulationAge58M;
	public int PopulationAge58W;
	public int PopulationAge59M;
	public int PopulationAge59W;
	public int PopulationAge60M;
	public int PopulationAge60W;
	public int PopulationAge61M;
	public int PopulationAge61W;
	public int PopulationAge62M;
	public int PopulationAge62W;
	public int PopulationAge63M;
	public int PopulationAge63W;
	public int PopulationAge64M;
	public int PopulationAge64W;
	public int PopulationAge65M;
	public int PopulationAge65W;
	public int PopulationAge66M;
	public int PopulationAge66W;
	public int PopulationAge67M;
	public int PopulationAge67W;
	public int PopulationAge68M;
	public int PopulationAge68W;
	public int PopulationAge69M;
	public int PopulationAge69W;
	public int PopulationAge70M;
	public int PopulationAge70W;
	
	public float minBirthRateJung = 0.02f;
	public float maxBirthRateJung = 0.07f;
	public float minDeathRateJung = 0f;
	public float maxDeathRateJung = 0.09f;
	public float minDeathRateOld = 0.01f;
	public float maxDeathRateOld = 0.99f;
	
	public CellData GetCurrentCell()
	{
		return currentCell;
	}
}